@startuml
'Transition Inputs: {v_p0 -> '{"unit": 0}'}
'Marking (State): {p0={'{"unit": 0}'}}
(0) --> (1): RootConcreteTSpec_ExecutePrinter_0
'Transition Inputs: {v_PrintFactoryA3DPrinterInput -> '{"Flow_1u2qmtt": {"unit": 0}, "request": {"id": 1, "resolution": "PrintResolution::LOW", "scale": 50.0, "color": "ColorType::MONOCHROME", "opType": "OperationType::PRINT"}, "variants": {"version": "", "release": ""}, "Event_0jcg6zx": {"unit": 0}, "printResult": {"verdict": "Outcome::OK"}, "printReport": {"id": 0}, "printJob": {"id": 0, "resolution": "PrintResolution::LOW", "scale": 0.0, "color": "ColorType::MONOCHROME", "opType": "OperationType::PREP"}, "corrections": {"correctionsMap": {}, "id": 0}, "Flow_0iaelzn": {"unit": 0}, "Event_0mxx05p": {"unit": 0}}'}
'Marking (State): {PrintFactoryA3DPrinterInput={'{"Flow_1u2qmtt": {"unit": 0}, "request": {"id": 1, "resolution": "PrintResolution::LOW", "scale": 50.0, "color": "ColorType::MONOCHROME", "opType": "OperationType::PRINT"}, "variants": {"version": "", "release": ""}, "Event_0jcg6zx": {"unit": 0}, "printResult": {"verdict": "Outcome::OK"}, "printReport": {"id": 0}, "printJob": {"id": 0, "resolution": "PrintResolution::LOW", "scale": 0.0, "color": "ColorType::MONOCHROME", "opType": "OperationType::PREP"}, "corrections": {"correctionsMap": {}, "id": 0}, "Flow_0iaelzn": {"unit": 0}, "Event_0mxx05p": {"unit": 0}}'}, p1={'{"unit": 0}'}}
(1) -[#darkorange]-> (2): RootRESPONSE_Activation
'Transition Inputs: {v_p1 -> '{"unit": 0}'}
'Marking (State): {ctx={'{"id": 1}'}, p1={'{"unit": 0}'}, split={'{"unit": 0}'}}
(2) --> (3): RootConcreteTSpec_ExecutePrinter_1
'Transition Inputs: {v_split -> '{"unit": 0}', v_PrintFactoryA3DPrinterInput -> '{"Flow_1u2qmtt": {"unit": 0}, "request": {"id": 1, "resolution": "PrintResolution::LOW", "scale": null, "color": "ColorType::MONOCHROME", "opType": "OperationType::PREP"}, "variants": {"version": "", "release": ""}, "Event_0jcg6zx": {"unit": 0}, "printResult": {"verdict": "Outcome::OK"}, "printReport": {"id": 0}, "printJob": {"id": 0, "resolution": "PrintResolution::LOW", "scale": 0.0, "color": "ColorType::MONOCHROME", "opType": "OperationType::PREP"}, "corrections": {"correctionsMap": {}, "id": 0}, "Flow_0iaelzn": {"unit": 0}, "Event_0mxx05p": {"unit": 0}}', v_ctx -> '{"id": 1}'}
'Marking (State): {PrintFactoryA3DPrinterInput={'{"Flow_1u2qmtt": {"unit": 0}, "request": {"id": 1, "resolution": "PrintResolution::LOW", "scale": null, "color": "ColorType::MONOCHROME", "opType": "OperationType::PREP"}, "variants": {"version": "", "release": ""}, "Event_0jcg6zx": {"unit": 0}, "printResult": {"verdict": "Outcome::OK"}, "printReport": {"id": 0}, "printJob": {"id": 0, "resolution": "PrintResolution::LOW", "scale": 0.0, "color": "ColorType::MONOCHROME", "opType": "OperationType::PREP"}, "corrections": {"correctionsMap": {}, "id": 0}, "Flow_0iaelzn": {"unit": 0}, "Event_0mxx05p": {"unit": 0}}'}, ctx={'{"id": 1}'}, p2={'{"unit": 0}'}, split={'{"unit": 0}'}}
(3) -[#darkorange]-> (4): RootRESPONSE_Target
'Transition Inputs: {v_p2 -> '{"unit": 0}'}
'Marking (State): {p2={'{"unit": 0}'}}
(4) --> (5): RootConcreteTSpec_ExecutePrinter_2
'Transition Inputs: {v_PrintFactoryA3DPrinterInput -> '{"Flow_1u2qmtt": {"unit": 0}, "request": {"id": 2, "resolution": "PrintResolution::MED", "scale": 75.0, "color": "ColorType::COLOR", "opType": "OperationType::PRINT"}, "variants": {"version": "", "release": ""}, "Event_0jcg6zx": {"unit": 0}, "printResult": {"verdict": "Outcome::OK"}, "printReport": {"id": 0}, "printJob": {"id": 0, "resolution": "PrintResolution::LOW", "scale": 0.0, "color": "ColorType::MONOCHROME", "opType": "OperationType::PREP"}, "corrections": {"correctionsMap": {}, "id": 0}, "Flow_0iaelzn": {"unit": 0}, "Event_0mxx05p": {"unit": 0}}'}
'Marking (State): {PrintFactoryA3DPrinterInput={'{"Flow_1u2qmtt": {"unit": 0}, "request": {"id": 2, "resolution": "PrintResolution::MED", "scale": 75.0, "color": "ColorType::COLOR", "opType": "OperationType::PRINT"}, "variants": {"version": "", "release": ""}, "Event_0jcg6zx": {"unit": 0}, "printResult": {"verdict": "Outcome::OK"}, "printReport": {"id": 0}, "printJob": {"id": 0, "resolution": "PrintResolution::LOW", "scale": 0.0, "color": "ColorType::MONOCHROME", "opType": "OperationType::PREP"}, "corrections": {"correctionsMap": {}, "id": 0}, "Flow_0iaelzn": {"unit": 0}, "Event_0mxx05p": {"unit": 0}}'}, p3={'{"unit": 0}'}}
(5) -[#darkorange]-> (6): RootRESPONSE_Activation
'Transition Inputs: {v_p3 -> '{"unit": 0}'}
'Marking (State): {ctx={'{"id": 2}'}, p3={'{"unit": 0}'}, split={'{"unit": 0}'}}
(6) --> (7): RootConcreteTSpec_ExecutePrinter_3
'Transition Inputs: {v_split -> '{"unit": 0}', v_PrintFactoryA3DPrinterInput -> '{"Flow_1u2qmtt": {"unit": 0}, "request": {"id": 2, "resolution": "PrintResolution::MED", "scale": null, "color": "ColorType::COLOR", "opType": "OperationType::PREP"}, "variants": {"version": "", "release": ""}, "Event_0jcg6zx": {"unit": 0}, "printResult": {"verdict": "Outcome::OK"}, "printReport": {"id": 0}, "printJob": {"id": 0, "resolution": "PrintResolution::LOW", "scale": 0.0, "color": "ColorType::MONOCHROME", "opType": "OperationType::PREP"}, "corrections": {"correctionsMap": {}, "id": 0}, "Flow_0iaelzn": {"unit": 0}, "Event_0mxx05p": {"unit": 0}}', v_ctx -> '{"id": 2}'}
'Marking (State): {PrintFactoryA3DPrinterInput={'{"Flow_1u2qmtt": {"unit": 0}, "request": {"id": 2, "resolution": "PrintResolution::MED", "scale": null, "color": "ColorType::COLOR", "opType": "OperationType::PREP"}, "variants": {"version": "", "release": ""}, "Event_0jcg6zx": {"unit": 0}, "printResult": {"verdict": "Outcome::OK"}, "printReport": {"id": 0}, "printJob": {"id": 0, "resolution": "PrintResolution::LOW", "scale": 0.0, "color": "ColorType::MONOCHROME", "opType": "OperationType::PREP"}, "corrections": {"correctionsMap": {}, "id": 0}, "Flow_0iaelzn": {"unit": 0}, "Event_0mxx05p": {"unit": 0}}'}, ctx={'{"id": 2}'}, p4={'{"unit": 0}'}, split={'{"unit": 0}'}}
(7) -[#darkorange]-> (8): RootRESPONSE_Target
'Transition Inputs: {v_p4 -> '{"unit": 0}'}
'Marking (State): {p4={'{"unit": 0}'}}
(8) --> (9): RootConcreteTSpec_ExecutePrinter_4
'Transition Inputs: {v_PrintFactoryA3DPrinterInput -> '{"Flow_1u2qmtt": {"unit": 0}, "request": {"id": 3, "resolution": "PrintResolution::HIGH", "scale": 75.0, "color": "ColorType::COLOR", "opType": "OperationType::PRINT"}, "variants": {"version": "", "release": ""}, "Event_0jcg6zx": {"unit": 0}, "printResult": {"verdict": "Outcome::OK"}, "printReport": {"id": 0}, "printJob": {"id": 0, "resolution": "PrintResolution::LOW", "scale": 0.0, "color": "ColorType::MONOCHROME", "opType": "OperationType::PREP"}, "corrections": {"correctionsMap": {}, "id": 0}, "Flow_0iaelzn": {"unit": 0}, "Event_0mxx05p": {"unit": 0}}'}
'Marking (State): {PrintFactoryA3DPrinterInput={'{"Flow_1u2qmtt": {"unit": 0}, "request": {"id": 3, "resolution": "PrintResolution::HIGH", "scale": 75.0, "color": "ColorType::COLOR", "opType": "OperationType::PRINT"}, "variants": {"version": "", "release": ""}, "Event_0jcg6zx": {"unit": 0}, "printResult": {"verdict": "Outcome::OK"}, "printReport": {"id": 0}, "printJob": {"id": 0, "resolution": "PrintResolution::LOW", "scale": 0.0, "color": "ColorType::MONOCHROME", "opType": "OperationType::PREP"}, "corrections": {"correctionsMap": {}, "id": 0}, "Flow_0iaelzn": {"unit": 0}, "Event_0mxx05p": {"unit": 0}}'}, p5={'{"unit": 0}'}}
(9) -[#darkorange]-> (10): RootRESPONSE_Activation
'Transition Inputs: {v_p5 -> '{"unit": 0}'}
'Marking (State): {ctx={'{"id": 3}'}, p5={'{"unit": 0}'}, split={'{"unit": 0}'}}
(10) --> (11): RootConcreteTSpec_ExecutePrinter_5
'Transition Inputs: {v_split -> '{"unit": 0}', v_PrintFactoryA3DPrinterInput -> '{"Flow_1u2qmtt": {"unit": 0}, "request": {"id": 3, "resolution": "PrintResolution::HIGH", "scale": null, "color": "ColorType::COLOR", "opType": "OperationType::PREP"}, "variants": {"version": "", "release": ""}, "Event_0jcg6zx": {"unit": 0}, "printResult": {"verdict": "Outcome::OK"}, "printReport": {"id": 0}, "printJob": {"id": 0, "resolution": "PrintResolution::LOW", "scale": 0.0, "color": "ColorType::MONOCHROME", "opType": "OperationType::PREP"}, "corrections": {"correctionsMap": {}, "id": 0}, "Flow_0iaelzn": {"unit": 0}, "Event_0mxx05p": {"unit": 0}}', v_ctx -> '{"id": 3}'}
'Marking (State): {PrintFactoryA3DPrinterInput={'{"Flow_1u2qmtt": {"unit": 0}, "request": {"id": 3, "resolution": "PrintResolution::HIGH", "scale": null, "color": "ColorType::COLOR", "opType": "OperationType::PREP"}, "variants": {"version": "", "release": ""}, "Event_0jcg6zx": {"unit": 0}, "printResult": {"verdict": "Outcome::OK"}, "printReport": {"id": 0}, "printJob": {"id": 0, "resolution": "PrintResolution::LOW", "scale": 0.0, "color": "ColorType::MONOCHROME", "opType": "OperationType::PREP"}, "corrections": {"correctionsMap": {}, "id": 0}, "Flow_0iaelzn": {"unit": 0}, "Event_0mxx05p": {"unit": 0}}'}, ctx={'{"id": 3}'}, p6={'{"unit": 0}'}, split={'{"unit": 0}'}}
(11) -[#darkorange]-> (12): RootRESPONSE_Target
'Marking (State): {finalPlace={'{"unit": 0}'}}
title State space: 13 nodes and 12 edges
@enduml
